// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '[REDACTED_FOR_PUBLIC]',
    appId: '[REDACTED_FOR_PUBLIC]',
    messagingSenderId: '[REDACTED_FOR_PUBLIC]',
    projectId: 'studentcore-demo',
    authDomain: '[REDACTED_FOR_PUBLIC]',
    storageBucket: '[REDACTED_FOR_PUBLIC]',
    measurementId: '[REDACTED_FOR_PUBLIC]',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '[REDACTED_FOR_PUBLIC]',
    appId: '[REDACTED_FOR_PUBLIC]',
    messagingSenderId: '[REDACTED_FOR_PUBLIC]',
    projectId: 'studentcore-demo',
    storageBucket: '[REDACTED_FOR_PUBLIC]',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '[REDACTED_FOR_PUBLIC]',
    appId: '[REDACTED_FOR_PUBLIC]',
    messagingSenderId: '[REDACTED_FOR_PUBLIC]',
    projectId: 'studentcore-demo',
    storageBucket: '[REDACTED_FOR_PUBLIC]',
    iosBundleId: '[REDACTED_FOR_PUBLIC]',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '[REDACTED_FOR_PUBLIC]',
    appId: '[REDACTED_FOR_PUBLIC]',
    messagingSenderId: '[REDACTED_FOR_PUBLIC]',
    projectId: 'studentcore-demo',
    storageBucket: '[REDACTED_FOR_PUBLIC]',
    iosBundleId: '[REDACTED_FOR_PUBLIC]',
  );
}
