// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASHutGOefyuvKDrO0v6vVEahE2BIJYSWc',
    appId: '1:679307212751:web:b5886453ff609aa00b04ba',
    messagingSenderId: '679307212751',
    projectId: 'studentcore-35124',
    authDomain: 'studentcore-35124.firebaseapp.com',
    storageBucket: 'studentcore-35124.appspot.com',
    measurementId: 'G-G6RNR9DXW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmUXtY3ukf-HRE-l95SH9FrcnNDFIXBA',
    appId: '1:679307212751:android:fdaff642d705e9220b04ba',
    messagingSenderId: '679307212751',
    projectId: 'studentcore-35124',
    storageBucket: 'studentcore-35124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ihSHYXsgGlLxC6VtrsHL-kAbiYwU6R8',
    appId: '1:679307212751:ios:8c8f1d6bbfd14e020b04ba',
    messagingSenderId: '679307212751',
    projectId: 'studentcore-35124',
    storageBucket: 'studentcore-35124.appspot.com',
    iosBundleId: 'com.example.studentCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ihSHYXsgGlLxC6VtrsHL-kAbiYwU6R8',
    appId: '1:679307212751:ios:aa86d2d5d6fb7b360b04ba',
    messagingSenderId: '679307212751',
    projectId: 'studentcore-35124',
    storageBucket: 'studentcore-35124.appspot.com',
    iosBundleId: 'com.example.studentCore.RunnerTests',
  );
}
